title: 'Công ty TNHH Giải Pháp Hệ Thống Xanh ( Green System Solutions)'
default_lang: vi
author:
  name: 'Chuong NGUYEN'
  email: info@hethongxanh.vn
taxonomies:
  - category
  - tag
metadata:
  description: 'GREEN SYSTEM SOLUTIONS - A Service Oriented Architecture firm offering ERP Implementation, Project Management, Transformation; Technology Infrastructure solutions, the entire IT life cycle for your business'
  Keywords: 'Giải pháp quản lý dự án và danh mục đầu tư, project management and portfolio management , ERP consultant, Management Consulting, Project Management, ERP Implementation, Service Oriented Architecture, Change Management, HR Consulting, Technology Infrastructure, Software Testing Solutions, Consulting Services, Consulting Firm, ERP, MIS, CRM, HRM, BI, FM'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
