enabled: true
favicon:
  user/themes/big-picture/images/logo.jpg:
    name: logo.jpg
    type: image/jpeg
    size: 3902
    path: user/themes/big-picture/images/logo.jpg
error_background_image:
  user/themes/big-picture/images/bg1.jpg:
    name: bg1.jpg
    type: image/jpeg
    size: 89627
    path: user/themes/big-picture/images/bg1.jpg
