enabled: true
production-mode: true
grid-size: grid-md
header-fixed: true
header-animated: true
header-dark: false
header-transparent: true
sticky-footer: true
blog-page: /blog
spectre:
  exp: false
  icons: false
custom_logo:
  user/themes/quark/images/logo/logo.jpg:
    name: logo.jpg
    type: image/jpeg
    size: 3902
    path: user/themes/quark/images/logo/logo.jpg
custom_logo_mobile:
  user/themes/quark/images/logo/logo-design.jpg:
    name: logo-design.jpg
    type: image/jpeg
    size: 9827
    path: user/themes/quark/images/logo/logo-design.jpg
